import glob
import pandas as pd

workdir: config['workdir']
#singularity: config['sif']
#configfile: 'config.yaml'

include: 'rules/common.smk'

# load assemblies into dataframe 
genseqs = pd.read_csv(
        Path(workflow.basedir).parent / config['assems'],
        sep='\t', 
        header=None, 
        names=['name', 'fasta']
)

wildcard_constraints:
    comm=r"\d+"

rule all:
    input:
       ## leaving this here as an example
       #expand(
       #    '{bucket}/public/{u.name}/{u.name}.clean.fa',
       #    bucket=config['bucket'],
       #    u=genseqs.itertuples()
       #),
        expand(
           #'{bucket}/public/combine/chrom.max_divergence.txt',
            '{bucket}/okay.txt',
            bucket=config['bucket']
        ),

include: 'rules/prep_seqs.smk'
include: 'rules/communities.smk'
include: 'rules/pggb.smk'
