
workdir: /scratch.global/mccuem_PGGBAKE
bucket: results
assems: 'config/assemblies.tsv'

pggb:
  ref_call: CHM13
  haps: 3
  segm_len: [5000] # [10000, 35000, 50000, 100000]
  perc_ident: [90] # [90, 95, 96, 97, 98, 99]
  min_mat_len: [23] # [10, 23, 35, 50, 150, 300]
  poa_len: ['700.900.1100'] # ['700.900.1100', '3079.3559', '13033.13117']
  image: 'docker://ghcr.io/pangenome/pggb:latest'

#mc:
#  del_filter: 10000000
#  max_len: 10000
#  clip: 10000
#  filter: 5 # increased from 2 to 5 (~10% of input)
#  other_contig: 'chrOther'
#  out_name: 'epic-v0.2-mc'
#  vcf_ref: [RefT2Tv5, RefEquCab3] # removed friesian and warmblood from auto vcf gen
#  image: 'docker://quay.io/comparative-genomics-toolkit/cactus:v2.9.0'

image:
  mash: 'docker://docker.io/jonahcullen/mash:2.3'
  panacus: 'docker://docker.io/jonahcullen/panacus:0.2.4'
  samtools: 'docker://docker.io/jonahcullen/samtools:1.16.1' 
  vg: 'docker://quay.io/vgteam/vg:v1.60.0'
  seqkit: 'docker://docker.io/jonahcullen/seqkit-go:2.8.2'
  pandepth: 'docker://docker.io/jonahcullen/pandepth:2.25'
  odgi: 'docker://pangenome/odgi:1730924146' # v0.9.0-7-gf4c1671c
  bedtools: 'docker://docker.io/jonahcullen/bedtools:2.31.0'

